apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-conf
  namespace: hasura
data:
  controller-conf.json: |
    {
        "apiServer" : {
            "type": "auto"
        },
        "imageRegistry" : "hasuraci",
        "projectNamespace" : "default",
        "controllerNamespace" : "hasura",
        "provider" : {
            "Local": {
                "gatewayIp" : "10.24.4.9",
                "sshPort" : "2022",
                "persistentDirectory" : "/data"
            }
        },
        "projectConfigMap" : "hasura-project-conf",
        "statusConfigMap" : "hasura-project-status",
        "logLevel" : "debug"
    }
