apiVersion: v1
kind: Pod
metadata:
  name: platform-init-v0.12.3
  namespace: hasura
spec:
  containers:
  - name: shukra
    image: hasuraci/shukra:v0.12.3
    command:
    - shukra
    - -c
    - /conf/controller-conf.json
    - init
    volumeMounts:
    - name: controller-conf
      mountPath: /conf
  volumes:
  - name: controller-conf
    configMap:
      name: controller-conf
  restartPolicy: Never
